- backend/build.gradle
- backend/src/main/java/com/woowacourse/ternoko/dto/CoachesResponse.java
- backend/src/test/java/com/woowacourse/ternoko/acceptance/AcceptanceTest.java
- #11 
- 테스트 격리에 대해서 고민해보기 
close #11
> [BE] ERROR 사항을 수정한다. 

- backend/src/main/java/com/woowacourse/ternoko/controller/MemberController.java
- backend/src/main/java/com/woowacourse/ternoko/controller/ReservationController.java
- backend/src/main/java/com/woowacourse/ternoko/domain/Location.java
- backend/src/main/java/com/woowacourse/ternoko/dto/FormItemRequest.java
- backend/src/main/java/com/woowacourse/ternoko/dto/ReservationRequest.java
- backend/src/main/java/com/woowacourse/ternoko/repository/FormItemRepository.java
- backend/src/main/java/com/woowacourse/ternoko/repository/InterviewRepository.java
- backend/src/main/java/com/woowacourse/ternoko/repository/ReservationRepository.java
- backend/src/main/java/com/woowacourse/ternoko/service/MemberService.java
- backend/src/main/java/com/woowacourse/ternoko/service/ReservationService.java
- backend/src/test/java/com/woowacourse/ternoko/acceptance/AcceptanceTest.java
- backend/src/test/java/com/woowacourse/ternoko/acceptance/ReservationAcceptanceTest.java
- backend/src/test/java/com/woowacourse/ternoko/service/ReservationServiceTest.java
> [BE] 면담 예약 기능 구현

- backend/src/main/java/com/woowacourse/ternoko/controller/ReservationController.java
- backend/src/main/java/com/woowacourse/ternoko/domain/Interview.java
- backend/src/main/java/com/woowacourse/ternoko/domain/Member.java
- backend/src/main/java/com/woowacourse/ternoko/dto/ReservationResponse.java
- backend/src/main/java/com/woowacourse/ternoko/service/MemberService.java
- backend/src/main/java/com/woowacourse/ternoko/service/ReservationService.java
- backend/src/test/java/com/woowacourse/ternoko/acceptance/ReservationAcceptanceTest.java
- backend/src/test/java/com/woowacourse/ternoko/fixture/ReservationFixture.java
- backend/src/test/java/com/woowacourse/ternoko/service/ReservationServiceTest.java
> [BE] 면담 예약 상세 내역 조회 기능 구현

- backend/src/main/java/com/woowacourse/ternoko/controller/ReservationController.java
- backend/src/main/java/com/woowacourse/ternoko/domain/Interview.java
- backend/src/main/java/com/woowacourse/ternoko/dto/ReservationRequest.java
- backend/src/main/java/com/woowacourse/ternoko/dto/ReservationResponse.java
- backend/src/main/java/com/woowacourse/ternoko/service/MemberService.java
- backend/src/main/java/com/woowacourse/ternoko/service/ReservationService.java
- backend/src/test/java/com/woowacourse/ternoko/acceptance/AcceptanceTest.java
- backend/src/test/java/com/woowacourse/ternoko/acceptance/ReservationAcceptanceTest.java
- backend/src/test/java/com/woowacourse/ternoko/fixture/ReservationFixture.java
- backend/src/test/java/com/woowacourse/ternoko/service/MemberServiceTest.java
- backend/src/test/java/com/woowacourse/ternoko/service/ReservationServiceTest.java
- #15 
- #21 
- API 스펙 변경 
- #20 
- #19 
close #15 
close #21 
close #19 
close #25
> [BE] 면담 목록 조회 기능 구현

- backend/src/main/resources/application.yml
- backend/src/test/java/com/woowacourse/ternoko/acceptance/AcceptanceTest.java
- backend/src/test/resources/application.yml
- #26 
- 프로덕션 DB는 MySQL 모드로 실행된다.
- 코치 더미데이터를 직접 추가해주어야 한다. 
close #26
> [BE] 프로덕션 DB에 코치 더미데이터 추가

- frontend/public/index.html
- frontend/src/AppRoutes.tsx
- frontend/src/api/index.ts
- frontend/src/components/@common/Button/styled.ts
- frontend/src/components/@common/ErrorMessage/styled.tsx
- frontend/src/components/Calendar/index.tsx
- frontend/src/components/Calendar/useCalendar.ts
- frontend/src/components/CoachProfile/CoachProfile.stories.tsx
- frontend/src/components/CoachProfile/styled.tsx
- frontend/src/components/Header/styled.ts
- frontend/src/components/Reservation/Reservation.stories.tsx
- frontend/src/components/Reservation/index.tsx
- frontend/src/components/Reservation/styled.ts
- frontend/src/components/TextAreaField/styled.tsx
- frontend/src/pages/HomePage/index.tsx
- frontend/src/pages/ReservationApplyPage/index.tsx
- frontend/src/pages/ReservationApplyPage/styled.tsx
- frontend/src/pages/ReservationCompletePage/index.tsx
- frontend/src/styles/GlobalStyle.tsx
- frontend/src/types/domain.ts
> [FE] feat: UI / UX를 수정한다.

- frontend/src/api/index.ts
- frontend/src/context/CalendarProvider.tsx
- frontend/src/pages/CoachReservationCreatePage/index.tsx
- frontend/src/types/domain.ts
- frontend/src/utils.ts
- [ #55 ] 
close #55 
close #65
> [FE] feat: Calendar 고도화를 한다.

- frontend/src/components/Calendar/index.tsx
- frontend/src/components/Calendar/styled.tsx
- frontend/src/context/CalendarProvider.tsx
- frontend/src/pages/CoachReservationCreatePage/index.tsx
- frontend/src/pages/ReservationApplyPage/index.tsx
- frontend/src/pages/ReservationApplyPage/styled.tsx
- frontend/src/types/domain.ts
- [#69 ] 
- 오늘 날짜 초과한 날짜들만 주세용!
<br>
- 이미 다른 크루가 예약한 시간 필터링 해주세용!
close #69
> [FE] feat: 크루 입장에서, 코치 되는시간 조회 API를 연결한다. 

- frontend/src/AppRoutes.tsx
- frontend/src/components/Header/index.tsx
- frontend/src/components/Header/styled.ts
> [FE] feat: Header UI/UX 개선

- frontend/docs/REQUIREMENTS.MD
- frontend/src/AppRoutes.tsx
- frontend/src/components/@common/TitleBox/index.tsx
- frontend/src/components/InputAreaField/index.tsx
- frontend/src/components/InputAreaField/styled.tsx
- frontend/src/components/TextAreaField/index.tsx
- frontend/src/components/TextAreaField/styled.tsx
- frontend/src/pages/LoginPage/index.tsx
- frontend/src/pages/LoginPage/styled.tsx
- frontend/src/pages/LoginRegisterPage/index.tsx
- frontend/src/pages/LoginRegisterPage/styled.tsx
- frontend/src/pages/MyPage/index.tsx
- frontend/src/pages/MyPage/styled.tsx
- frontend/src/pages/ReservationApplyPage/index.tsx
- frontend/src/styles/GlobalStyle.tsx
- frontend/src/styles/theme.ts
- frontend/src/validations.ts
> [FE] feat: 로그인 페이지와 마이페이지를 개발한다.

- backend/src/test/java/com/woowacourse/ternoko/acceptance/CoachAcceptanceTest.java
- backend/src/test/java/com/woowacourse/ternoko/acceptance/MemberAcceptanceTest.java
- backend/src/test/java/com/woowacourse/ternoko/fixture/CoachAvailableTimeFixture.java
- backend/src/test/java/com/woowacourse/ternoko/service/CoachServiceTest.java
- backend/src/test/java/com/woowacourse/ternoko/service/ReservationServiceTest.java
- 서버 구동을 위해 오류 해결한 뒤 PR 요청 드립니다. 추후 Slack 알람 기능에서 변경되는 부분이 많아 다른 feature에서 수정하도록하겠습니다.  
close #108
> fix: 코치 되는 시간 픽스쳐 관련(과거시간) 문제 수정

- .github/workflows/backend-test
- backend/build.gradle
- backend/config/ternoko-checkstyle.xml
- backend/config/wooteco-style.xml
- backend/src/main/java/com/woowacourse/ternoko/common/AuthInterceptor.java
- backend/src/main/java/com/woowacourse/ternoko/config/ClassConfig.java
- backend/src/main/java/com/woowacourse/ternoko/config/DatabaseInitializer.java
- backend/src/main/java/com/woowacourse/ternoko/domain/AvailableDateTime.java
- backend/src/main/java/com/woowacourse/ternoko/dto/NicknameResponse.java
- backend/src/main/java/com/woowacourse/ternoko/dto/ReservationResponse.java
- backend/src/main/java/com/woowacourse/ternoko/dto/request/AvailableDateTimeRequest.java
- backend/src/main/java/com/woowacourse/ternoko/dto/request/AvailableDateTimesRequest.java
- backend/src/main/java/com/woowacourse/ternoko/repository/AvailableDateTimeRepository.java
- backend/src/main/java/com/woowacourse/ternoko/repository/CoachRepository.java
- backend/src/main/java/com/woowacourse/ternoko/service/CoachService.java
- backend/src/main/java/com/woowacourse/ternoko/service/MemberService.java
- backend/src/main/java/com/woowacourse/ternoko/support/SlackAlarm.java
- backend/src/main/resources/log4j2-local.xml
- 테스트가 깨지는지 확인한다.
- 코딩 컨벤션이 맞는지 확인한다.
없음
close #118
> [BE] 자동화 테스트를 세팅한다.

- backend/config/wooteco-style.xml
- backend/src/main/java/com/woowacourse/ternoko/common/exception/BadRequestException.java
- backend/src/main/java/com/woowacourse/ternoko/common/exception/CommonException.java
- backend/src/main/java/com/woowacourse/ternoko/common/exception/UnauthorizedException.java
- backend/src/main/java/com/woowacourse/ternoko/common/exception/advice/GlobalControllerAdvice.java
- `BadRequestException`, `UnauthorizedException` 이 `CommonException`을 상속받도록 수정했습니다.
- `ControllerAdvice`를 패키지로 따로 구분하였습니다.
- `ControllerAdvice`에서 `SqlException`을 잡도록 수정했습니다.
close #138
> [BE] feat: exception 구조 변경 및 sqlException Handler 추가

- backend/src/main/java/com/woowacourse/ternoko/dto/ReservationResponse.java
- backend/src/test/java/com/woowacourse/ternoko/service/CoachServiceTest.java
- backend/static/docs/api.html
- 현재 되는 시간 Update 관련하여 추가 논의 필요
ReservationResponse - status 필드 추가 
close #152
> [BE] fix: ReservationResponse Status 추가 

- backend/README.md
- backend/src/main/java/com/woowacourse/ternoko/controller/ReservationController.java
- backend/src/main/java/com/woowacourse/ternoko/dto/InterviewResponse.java
- backend/src/main/java/com/woowacourse/ternoko/repository/InterviewRepository.java
- backend/src/main/java/com/woowacourse/ternoko/service/ReservationService.java
- backend/src/test/java/com/woowacourse/ternoko/acceptance/ReservationAcceptanceTest.java
- backend/src/test/java/com/woowacourse/ternoko/service/ReservationServiceTest.java
- 정렬방식은 이번엔 jpql로 했습니다. 훨씬 더 간편해보이는데 의견 달아주시면 감사하겠습니다.
close #140 
close #92
> [BE] feat: 크루의 면담목록 조회 API 수정

- backend/src/main/java/com/woowacourse/ternoko/config/DatabaseInitializer.java
> [BE] fix: 록바 코치 관련 데이터 추가

- backend/src/main/java/com/woowacourse/ternoko/support/SlackAlarm.java
> [BE] fix: 슬랙 알람 시간 포맷 변경

- backend/src/main/java/com/woowacourse/ternoko/dto/InterviewResponse.java
- backend/src/main/java/com/woowacourse/ternoko/dto/ReservationResponse.java
- 코치 및 크루 이미지 필드 추가 
- 현재 코치 이미지만 반환하고 있었음.
close #169
> [BE] fix: 면담 조회 시 코치/크루 이미지 응답값 추가

- backend/src/main/resources/application-local.yml
- backend/src/main/resources/log4j2-local.xml
- sql 관련 로그설정 로깅레벨을 바꿔서 로컬에서도 sql로그를 볼 수 있게 로깅레벨을 바꿨습니다.
- 서브모듈에서
- develop xml에서도 마찬가지로 sql로그를 볼 수 있게 로깅레벨을 바꿨습니다.
- 개발서버에 찍히는 SQL 로그가 이제 sql.log, sql_binder.log로 분리되어 찍히는게 아니라 sql.log 하나에 같이 찍히게 됩니다.
close #181
> [BE] chore: sql 로그 레벨 변경

- frontend/src/components/@common/Accordion/index.tsx
- frontend/src/components/ReservationDetailModal/index.tsx
- frontend/src/components/ReservationDetailModal/styled.ts
- frontend/src/pages/LoginRegisterPage/index.tsx
- frontend/src/pages/TestPage/index.tsx
> [FE] fix: 회원가입시, 프로필 안 뜨는 버그를 해결한다. 

- backend/src/main/java/com/woowacourse/ternoko/config/AuthenticationPrincipalArgumentResolver.java
- backend/src/main/java/com/woowacourse/ternoko/config/AuthenticationPrincipalConfig.java
- backend/src/main/java/com/woowacourse/ternoko/controller/AuthController.java
- backend/src/main/java/com/woowacourse/ternoko/domain/MemberType.java
- backend/src/main/java/com/woowacourse/ternoko/domain/Type.java
- backend/src/main/java/com/woowacourse/ternoko/dto/LoginResponse.java
- backend/src/main/java/com/woowacourse/ternoko/service/AuthService.java
- backend/src/test/java/com/woowacourse/ternoko/api/AuthControllerTest.java
- backend/src/test/java/com/woowacourse/ternoko/service/AuthServiceTest.java
> [BE] AccessToken 유효성 검사 로직 추가

- backend/src/docs/asciidoc/api.adoc
> [BE] docs: accessToken 유효성 검사 api docs 추가

- backend/src/docs/asciidoc/api.adoc
- backend/src/main/java/com/woowacourse/ternoko/availabledatetime/dto/AvailableDateTimeResponse.java
- backend/src/main/java/com/woowacourse/ternoko/availabledatetime/dto/AvailableDateTimesResponse.java
- backend/src/main/java/com/woowacourse/ternoko/service/CoachService.java
- backend/src/test/java/com/woowacourse/ternoko/acceptance/CoachAcceptanceTest.java
- backend/src/test/java/com/woowacourse/ternoko/acceptance/InterviewAcceptanceTest.java
- backend/src/test/java/com/woowacourse/ternoko/fixture/CoachAvailableTimeFixture.java
프론트에서 수정 전용 되는 시간 조회 API 요청이 들어옴. 
close #213
> [BE] fix: status AvailableDateTimeResponse 누락된 것 추가

- frontend/src/pages/InterviewApplyPage/index.tsx
- frontend/src/types/domain.ts
> feat: 면담 신청 페이지 바뀐 api에 맞춰 대응

- backend/src/main/java/com/woowacourse/ternoko/config/DatabaseInitializer.java
> [BE] feat: 록바 코치, 바니 크루 더미데이터 지우고, 터놓고 코치 더미데이터 추가

- backend/src/docs/asciidoc/api.adoc
- backend/src/main/java/com/woowacourse/ternoko/availabledatetime/dto/AvailableDateTimeRequest.java
- backend/src/main/java/com/woowacourse/ternoko/controller/CoachController.java
- backend/src/main/java/com/woowacourse/ternoko/interview/application/InterviewService.java
- backend/src/main/java/com/woowacourse/ternoko/interview/domain/Interview.java
- backend/src/main/java/com/woowacourse/ternoko/interview/presentation/InterviewController.java
- backend/src/main/java/com/woowacourse/ternoko/service/CoachService.java
- backend/src/test/java/com/woowacourse/ternoko/acceptance/AcceptanceTest.java
- backend/src/test/java/com/woowacourse/ternoko/acceptance/InterviewAcceptanceTest.java
- backend/src/test/java/com/woowacourse/ternoko/api/InterviewControllerTest.java
- backend/src/test/java/com/woowacourse/ternoko/interview/application/InterviewServiceTest.java
> [BE ] 코치가 면담 취소 시, 되는 시간을 유지할지, 삭제할지 분기 로직 추가

- backend/src/main/java/com/woowacourse/ternoko/interview/application/InterviewService.java
- backend/src/test/java/com/woowacourse/ternoko/interview/application/InterviewServiceTest.java
- 검증로직이 이해가 어렵고 다음날 면담도 예약이 안되는 문제가 있었습니다.
close #248
> [BE] fix: 다음날 면담 예약도 가능하도록 수정

- backend/.gitignore
- backend/src/docs/asciidoc/api.adoc
- backend/src/main/resources/static/docs/api.html
- backend/src/test/java/com/woowacourse/ternoko/api/CoachControllerTest.java
> [BE] fix: restDocs 에서 코치의 면담목록 조회 API가 다르게 나오던 문제 해결

- backend/src/main/java/com/woowacourse/ternoko/comment/application/CommentService.java
- backend/src/main/java/com/woowacourse/ternoko/comment/domain/Comment.java
- backend/src/main/java/com/woowacourse/ternoko/domain/InterviewStatusType.java
- backend/src/main/java/com/woowacourse/ternoko/domain/MemberType.java
- backend/src/main/java/com/woowacourse/ternoko/interview/domain/Interview.java
- backend/src/main/resources/static/docs/api.html
- backend/src/test/java/com/woowacourse/ternoko/interview/application/InterviewServiceTest.java
- backend/src/test/resources/data.sql
1. Interview - Comment 관련 메서드 분리 => CommentService
메서드명 Comment 중복 제거 (createComment() -> create())
2. InterviewStatus 검증 로직 InterviewStatusType 클래스로 이동
- 현재 InterviewStatus를 Enum타입으로 관리하고 검증 로직을 해당 enum 클래스에 작성
- Interview Status를 관리하는 로직에 대해 서로 의견을 나눠보면 좋을 것 같음.
- 지난 체스미션에 사용했던 것과 같이 상태패턴으로 관리하는 것은 어떨지?
- Ex) InterviewStatus(Interface) - comment(), create(), fix() 등의 메서드를 만들어서 각각의 상황에서 발생하는 예외나 작업을 처리하는  것은 어떨지
close #232
> [BE] refactor: Comment 코드 리팩터링

- backend/src/main/java/com/woowacourse/ternoko/availabledatetime/domain/AvailableDateTimeRepository.java
- backend/src/main/java/com/woowacourse/ternoko/service/CoachService.java
- backend/src/test/java/com/woowacourse/ternoko/availabledatetime/domain/AvailableDateTimeRepositoryTest.java
- 쿼리에서 OPEN된 시간만 조회하도록 수정했습니다.
- 쿼리에서 정렬하도록 수정했습니다.
close #265
> [BE] refactor: 코치가 면담 가능시간 조회시 OPEN된 시간만 반환하도록 수정

- backend/src/main/resources/application-local.yml
> [BE] chore: ddl을 create-drop으로 수정

- .github/workflows/sonarqube.yml
- backend/build.gradle
> feat: 소나큐브 설정 적용

- backend/README.md
- backend/src/docs/asciidoc/api.adoc
- backend/src/main/java/com/woowacourse/ternoko/comment/application/CommentService.java
- backend/src/main/java/com/woowacourse/ternoko/comment/domain/Comment.java
- backend/src/main/java/com/woowacourse/ternoko/comment/dto/CommentsResponse.java
- backend/src/main/java/com/woowacourse/ternoko/comment/presentation/CommentController.java
- backend/src/main/java/com/woowacourse/ternoko/domain/member/MemberType.java
- backend/src/main/java/com/woowacourse/ternoko/interview/domain/Interview.java
- backend/src/main/java/com/woowacourse/ternoko/interview/domain/InterviewStatusType.java
- backend/src/main/java/com/woowacourse/ternoko/login/application/AuthInterceptor.java
- backend/src/main/resources/static/docs/api.html
- backend/src/test/java/com/woowacourse/ternoko/api/ControllerTest.java
- backend/src/test/java/com/woowacourse/ternoko/comment/acceptance/CommentAcceptanceTest.java
- backend/src/test/java/com/woowacourse/ternoko/comment/application/CommentServiceTest.java
- backend/src/test/java/com/woowacourse/ternoko/comment/domain/CommentTest.java
- backend/src/test/java/com/woowacourse/ternoko/comment/presentation/CommentControllerTest.java
- backend/src/test/resources/data.sql
- interview에서 comment 상태를 없앴습니다.
- restDocs도 도입했습니다.
close #270 
close #280
> [BE] docs: comment 기능 restDocs 도입

- backend/src/main/java/com/woowacourse/ternoko/config/DatabaseInitializer.java
- backend/src/main/java/com/woowacourse/ternoko/interview/application/InterviewService.java
- backend/src/main/java/com/woowacourse/ternoko/interview/dto/AlarmResponse.java
- backend/src/main/java/com/woowacourse/ternoko/interview/presentation/InterviewController.java
- backend/src/main/java/com/woowacourse/ternoko/support/SlackAlarm.java
- backend/src/main/java/com/woowacourse/ternoko/support/SlackMessageType.java
- backend/src/test/java/com/woowacourse/ternoko/interview/application/InterviewServiceTest.java
- 기존
- 변경된 코치에게만 수정 메세지 전달 
- 현재
- 코치가 변경되지 않음.
- 코치 : 예약 수정 메세지
- 크루 : 예약 수정 메세지
- 코치가 변경됨.
- 기존 코치 : 예약 삭제 메세지
- 새로운 면담 코치 : 예약 등록 메세지
- 크루 : 예약 수정 메세지
close #284
> [BE] refactor: 면담 수정 시 코치 변경될 경우 알람 기능 수정

- backend/src/main/java/com/woowacourse/ternoko/config/DatabaseInitializer.java
> [BE] fix: 데이터베이스 이니셜라이저 데이터 수정

- backend/src/main/java/com/woowacourse/ternoko/availabledatetime/domain/AvailableDateTime.java
- backend/src/main/java/com/woowacourse/ternoko/availabledatetime/domain/AvailableDateTimeStatus.java
- backend/src/main/java/com/woowacourse/ternoko/comment/application/CommentService.java
- backend/src/main/java/com/woowacourse/ternoko/comment/presentation/CommentController.java
- backend/src/main/java/com/woowacourse/ternoko/common/exception/ExceptionType.java
- backend/src/main/java/com/woowacourse/ternoko/interview/application/InterviewService.java
- backend/src/main/java/com/woowacourse/ternoko/interview/domain/Interview.java
- backend/src/main/java/com/woowacourse/ternoko/interview/domain/formitem/FormItem.java
- backend/src/main/resources/static/docs/api.html
- backend/src/test/java/com/woowacourse/ternoko/acceptance/MemberAcceptanceTest.java
- backend/src/test/java/com/woowacourse/ternoko/api/AuthControllerTest.java
- backend/src/test/java/com/woowacourse/ternoko/availabledatetime/domain/AvailableDateTimeRepositoryTest.java
- backend/src/test/java/com/woowacourse/ternoko/comment/application/CommentServiceTest.java
- backend/src/test/java/com/woowacourse/ternoko/domain/InterviewTest.java
- backend/src/test/java/com/woowacourse/ternoko/interview/application/InterviewServiceTest.java
- backend/src/test/java/com/woowacourse/ternoko/service/AuthServiceTest.java
- 추후 낙관적락 걸기( #285 에서 논의 예정)
close #291 
close #292 
close #293
> [BE] refactor: 면담 수정 로직 개선 및 버그 수정

- backend/src/main/java/com/woowacourse/ternoko/interview/dto/CalendarResponse.java
- backend/src/main/resources/static/docs/api.html
- backend/src/test/java/com/woowacourse/ternoko/interview/application/InterviewServiceTest.java
- 코치화면에서 인터뷰상태를 읽어올 수 없다고 하여 인터뷰상태도 같이 반환하도록 수정했습니다.
- scheduleResponse 테스트중에서 필드값에 대한 테스트가 없어서 일단 인터뷰 필드를 검사하는 테스트만 추가했습니다.
close 
#318
> [BE] refactor: CalendarResponse에서 interviewStatus도 반환하도록 수정

- backend/src/main/java/com/woowacourse/ternoko/core/application/InterviewService.java
- backend/src/test/java/com/woowacourse/ternoko/service/InterviewServiceTest.java
기존의 filterCanceledInterview 메서드에서 sort 로직을 추가했는데 괜찮은 구조인지 피드백 부탁드립니다. 
close #346
> [BE] fix: 코치입장에서 면담목록 확인 시 시간에 따라 면담 목록을 정렬해서 반환한다.

- frontend/src/components/@common/Accordion/index.tsx
- frontend/src/components/@common/AskDeleteTimeModal/index.tsx
- frontend/src/components/@common/InterviewDetailModal/index.tsx
- frontend/src/components/Calendar/index.tsx
- frontend/src/components/CoachCalendar/styled.tsx
- frontend/src/constants.ts
- frontend/src/pages/CoachHomePage/index.tsx
- frontend/src/pages/InterviewApplyPage/index.tsx
> [FE] fix: QA 진행중 생겨난 버그를 수정한다.

- frontend/src/constants.ts
> [FE] fix: 슬랙 로그인 서버 URL을 변경한다. 

- frontend/src/constants.ts
> [FE] fix: 슬랙 로그인 서버 URL을 변경한다.

- frontend/src/AppRoutes.tsx
- frontend/src/components/@common/Accordion/styled.tsx
- frontend/src/components/@common/CommentModal/index.tsx
- frontend/src/components/@common/CommentModal/styled.tsx
- frontend/src/components/@common/InterviewDetailModal/styled.ts
- frontend/src/components/@common/Modal/styled.tsx
- frontend/src/components/@common/TitleBox/index.tsx
- frontend/src/components/Calendar/index.tsx
- frontend/src/components/Calendar/styled.tsx
- frontend/src/components/PrivateRoute/index.tsx
- frontend/src/context/CalendarProvider.tsx
- frontend/src/pages/CoachInterviewCreatePage/index.tsx
- frontend/src/pages/InterviewApplyPage/index.tsx
- frontend/src/pages/InterviewApplyPage/styled.tsx
- frontend/src/pages/LoginRegisterPage/index.tsx
- frontend/src/pages/MyPage/index.tsx
> [FE] feat: UI/UX 개선 및 버그 개선한다. 

- frontend/src/components/@common/ScrollContainer/styled.tsx
- frontend/src/components/Calendar/styled.tsx
- frontend/src/components/Time/styled.tsx
- frontend/src/pages/InterviewApplyPage/index.tsx
> [FE] fix: QA중 발생한 버그를 고친다.  

- frontend/src/components/@common/CalendarStyle/styled.tsx
- frontend/src/components/@common/CommentModal/index.tsx
- frontend/src/components/@common/ScrollContainer/styled.tsx
- frontend/src/components/@common/TitleBox/styled.tsx
- frontend/src/components/Calendar/index.tsx
- frontend/src/components/CoachCalendar/index.tsx
- frontend/src/context/CalendarProvider.tsx
- frontend/src/pages/CoachInterviewCreatePage/index.tsx
- frontend/src/pages/CoachInterviewCreatePage/styled.tsx
- frontend/src/pages/InterviewApplyPage/index.tsx
- frontend/src/pages/InterviewApplyPage/styled.tsx
- [#377 ] 
추후 작성...
close #377
> [FE] feat: QA중에 나온 버그를 수정한다.

- backend/src/main/java/com/woowacourse/ternoko/config/DatabaseInitializer.java
- backend/src/main/java/com/woowacourse/ternoko/core/application/CoachService.java
- backend/src/main/java/com/woowacourse/ternoko/core/domain/availabledatetime/AvailableDateTimeRepository.java
- backend/src/test/java/com/woowacourse/ternoko/domain/availabledatetime/AvailableDateTimeRepositoryTest.java
- 이슈 읽어보시면 원인적어놓았습니다.
- 서브쿼리에 coachId 조건까지 추가했습니다.
close #387
> [BE] fix: interivew 수정시 특정되는시간이 간헐적으로 여러개가 보이는 이슈 해결

- backend/build.gradle
- 지금까지 왜 됐는지 모르겠는데 GSON 빠지면 로그인 처리가 안됩니다.;
close #392
> [BE] chore: gson 추가

- backend/src/main/java/com/woowacourse/ternoko/core/domain/interview/Interview.java
- backend/src/main/java/com/woowacourse/ternoko/core/domain/interview/InterviewStatusType.java
- backend/src/test/java/com/woowacourse/ternoko/acceptance/CommentAcceptanceTest.java
- backend/src/test/java/com/woowacourse/ternoko/domain/interview/InterviewTest.java
- backend/src/test/java/com/woowacourse/ternoko/service/CommentServiceTest.java
> refactor: interviewStatus COMPLETE -> COMPLETED 변경

- frontend/src/components/@common/CommentModal/index.tsx
- frontend/src/components/CoachCalendar/index.tsx
- frontend/src/components/CoachProfile/index.tsx
- frontend/src/components/CoachProfile/styled.tsx
- frontend/src/components/Header/index.tsx
- frontend/src/components/Header/styled.ts
- frontend/src/components/InputAreaField/index.tsx
- frontend/src/components/Interview/index.tsx
- frontend/src/components/Interview/styled.ts
- frontend/src/components/TextAreaField/index.tsx
- frontend/src/pages/CoachInterviewCreatePage/index.tsx
- frontend/src/pages/CoachInterviewCreatePage/styled.tsx
- frontend/src/pages/HomePage/index.tsx
- frontend/src/pages/InterviewApplyPage/index.tsx
- frontend/src/pages/InterviewApplyPage/styled.tsx
- frontend/src/pages/LoginRegisterPage/index.tsx
- frontend/src/pages/MyPage/index.tsx
- frontend/src/pages/MyPage/styled.tsx
- frontend/src/styles/theme.ts
- frontend/src/types/domain.ts
> [FE] feat: 불편한 UI/UX를 수정하고 보완한다. 

- backend/src/main/java/com/woowacourse/ternoko/core/application/CoachService.java
- backend/src/test/java/com/woowacourse/ternoko/domain/availabledatetime/AvailableDateTimeRepositoryTest.java
되는 시간이 있는지 한달 단위로 계산하는 로직에서 당일 제외했습니다.
close #416
> [BE] fix: 한달 단위로 되는 시간 표시 로직에서 당일을 제외한다

- backend/src/main/java/com/woowacourse/ternoko/common/log/LogInterceptor.java
- backend/src/main/java/com/woowacourse/ternoko/core/domain/interview/InterviewRepository.java
- backend/src/test/java/com/woowacourse/ternoko/api/restdocs/RestDocsTestSupporter.java
https://necessary-sundial-178.notion.site/d575a364448440de9d4fd278f8fbcf52
close #431
> [BE] fix: 테스트에서 Log RequestBody 출력하게 수정

- backend/build.gradle
일단 `gson` 의존성을 제거해봤어요
close #439
> [BE] chore: gson 의존성 제거
